version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.staging
    ports:
      - 8001:8001
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 4 --timeout 120
    networks:
      - boilerplate_network
    volumes:
      - static_volume:/home/app/staticfiles
      - media_volume:/home/app/mediafiles

  web_api:
    build: ./nginx
    restart: always
    ports:
      - 8000:8000
    volumes:
      - static_volume:/code/staticfiles
      - media_volume:/code/mediafiles
    depends_on:
      - api
    networks:
      - boilerplate_network

  celery:
    build: .
    env_file:
      - ./.env.staging
    volumes:
      - .:/home/app
    command: celery -A config worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  smtp:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - boilerplate_network

volumes:
  static_volume:
  media_volume:

networks:
  boilerplate_network:
    driver: bridge
    name: boilerplate_network
