# Generated by Django 4.1.2 on 2024-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="about",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
