# Generated by Django 4.1.2 on 2024-01-30 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_about"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="entity_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
